version: "3.7"
services:
  backend:
    build: 
      context: ./yazilimots
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/yazilim_ots?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=224224
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.hibernate.show-sql=true
      - spring.jpa.properties.javax.persistence.validation.mode=none
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:5.6"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: yazilim_ots
      MYSQL_ROOT_PASSWORD: 224224

  frontend:
    build:
      context: ./otsFronted
    ports:
      - "3000:3000"
    networks:
      - yazilimotsfinal_network
    depends_on:
      - backend

networks:
  springapimysql-net:
  yazilimotsfinal_network:
